set(NETCDF_HDF5_OPTIONS
  "-DHDF5_ROOT=${CAPP_INSTALL_ROOT}/hdf5"
  "-DHDF5_FIND_DEBUG=OFF"
  "-DUSE_HDF5_SZIP=FALSE"
  "-DHDF5_IS_PARALLEL_MPIO=TRUE"
  "-DHDF5_HAS_COLL_METADATA_OPS=TRUE"
  "-DHAS_READCHUNKS=TRUE"
  "-DHAS_HDF5_ROS3=FALSE"
  "-DHAVE_HDF5_ZLIB=TRUE"
  "-DHDF5_USE_STATIC_LIBRARIES=TRUE")

capp_package(
  GIT_URL git@github.com:Unidata/netcdf-c.git
  COMMIT 06df257e22fae4b71032ae6317e4cb8a231020a7
  OPTIONS
  "-DCMAKE_C_COMPILER=${CALIBR8_MPICC}"
  "-DCMAKE_CXX_COMPILER=${CALIBR8_MPICXX}"
  "-DBUILD_SHARED_LIBS=OFF"
  "-DBUILD_TESTING=OFF"
  "-DBUILD_UTILITIES=ON"
  "-DENABLE_NETCDF_4=ON"
  "-DENABLE_PARALLEL4=ON"
  "-DENABLE_PNETCDF=OFF"
  "-DENABLE_DAP=OFF"
  "-DENABLE_CDF5=OFF"
  "-DENABLE_V2_API=OFF"
  "-DENABLE_EXAMPLES=OFF"
  "-DENABLE_TESTS=OFF"
  "-DENABLE_PLUGINS=OFF"
  ${NETCDF_HDF5_OPTIONS}
  ${NETCDF_OSX_OPTIONS}
  "-DHAVE_MPI_COMM_F2C=TRUE"
  "-DHAVE_MPI_INFO_F2C=TRUE"
  "-DZLIB_ROOT=${CAPP_INSTALL_ROOT}/zlib-ng"
  DEPENDENCIES
  hdf5
  zlib-ng
)
