capp_package(
  GIT_URL https://github.com/bgranzow/core
  COMMIT 483760eb46b89982d53e910b8732df406d0c1c3c
  OPTIONS
  "-DCMAKE_C_COMPILER=${CALIBR8_MPICC}"
  "-DCMAKE_CXX_COMPILER=${CALIBR8_MPICXX}"
  "-DENABLE_ZOLTAN=ON"
  "-DZOLTAN_LIBRARY=${CALIBR8_ZOLTAN_PATH}"
  "-DZOLTAN_INCLUDE_DIR=${CAPP_INSTALL_ROOT}/trilinos/include"
  "-DENABLE_STK=ON"
  "-DTrilinos_PREFIX=${CAPP_INSTALL_ROOT}/trilinos"
  "-DMETIS_LIBRARY=${CALIBR8_METIS_PATH}"
  "-DMETIS_INCLUDE_DIR=${CAPP_INSTALL_ROOT}/parmetis/include"
  "-DPARMETIS_LIBRARY=${CALIBR8_PARMETIS_PATH}"
  "-DPARMETIS_INCLUDE_DIR=${CAPP_INSTALL_ROOT}/parmetis/include"
  "-DENABLE_OMEGA_H=ON"
  "-DOmega_h_PREFIX=${CAPP_INSTALL_ROOT}/omega_h"
  "-DIS_TESTING=OFF"
  "-DZLIB_ROOT=${CAPP_INSTALL_ROOT}/zlib-ng"
  "-DZLIB_LIBRARY=${CALIBR8_ZLIB_PATH}"
  DEPENDENCIES 
  trilinos
  omega_h
  gmodel
  IGNORE_UNCOMMITTED
)
