set(CALIBR8_BUILD_TYPE RELWITHDEBINFO)
set(CALIBR8_BUILD_SHARED_LIBS ON)
set(CALIBR8_ZLIB_PATH "${CAPP_INSTALL_ROOT}/zlib-ng/lib/libz.so")
set(CALIBR8_ZOLTAN_PATH "${CAPP_INSTALL_ROOT}/trilinos/lib/libzoltan.so")
set(CALIBR8_METIS_PATH "${CAPP_INSTALL_ROOT}/parmetis/lib/libmetis.so")
set(CALIBR8_PARMETIS_PATH "${CAPP_INSTALL_ROOT}/parmetis/lib/libparmetis.so")
set(CALIBR8_RPATH_OPTIONS "-DCMAKE_SKIP_BUILD_RPATH=OFF"
  "-DCMAKE_BUILD_WITH_INSTALL_RPATH=OFF"
  "-DCMAKE_INSTALL_RPATH=${CAPP_INSTALL_ROOT}/calibr8/lib"
  "-DCMAKE_INSTALL_RPATH_USE_LINK_PATH=ON"
)
