set(CALIBR8_BUILD_SHARED_LIBS ON)
set(PARMETIS_OSX_RPATH_OPTIONS "-DCMAKE_MACOSX_RPATH=ON")
set(NETCDF_OSX_OPTIONS "-DNC_M4=/Library/Developer/CommandLineTools/usr/bin/gm4")
set(CALIBR8_ZLIB_PATH "${CAPP_INSTALL_ROOT}/zlib-ng/lib/libz.dylib")
set(CALIBR8_ZOLTAN_PATH "${CAPP_INSTALL_ROOT}/trilinos/lib/libzoltan.dylib")
set(CALIBR8_METIS_PATH "${CAPP_INSTALL_ROOT}/parmetis/lib/libmetis.dylib")
set(CALIBR8_PARMETIS_PATH "${CAPP_INSTALL_ROOT}/parmetis/lib/libparmetis.dylib")
set(CALIBR8_OSX_RPATH_OPTIONS "-DCMAKE_SKIP_BUILD_RPATH=OFF"
  "-DCMAKE_BUILD_WITH_INSTALL_RPATH=OFF"
  "-DCMAKE_INSTALL_RPATH=${CAPP_INSTALL_ROOT}/calibr8/lib"
  "-DCMAKE_INSTALL_RPATH_USE_LINK_PATH=ON"
)
