capp_package(
  GIT_URL git@github.com:sandialabs/calibr8.git
  COMMIT HEAD
  OPTIONS
  "-DCMAKE_CXX_COMPILER=${CALIBR8_MPICXX}"
  "-DBUILD_SHARED_LIBS=${CALIBR8_BUILD_SHARED_LIBS}"
  "-DBUILD_TESTING=ON"
  "-DTrilinos_ROOT=${CAPP_INSTALL_ROOT}/trilinos"
  "-DSCOREC_ROOT=${CAPP_INSTALL_ROOT}/scorec"
  "-DEIGEN_INCLUDE_DIRS=${CAPP_INSTALL_ROOT}/eigen/include/eigen3"
  "-DZLIB_ROOT=${CAPP_INSTALL_ROOT}/zlib-ng"
  "-DCMAKE_SKIP_BUILD_RPATH=OFF"
  "-DCMAKE_BUILD_WITH_INSTALL_RPATH=OFF"
  "-DCMAKE_INSTALL_RPATH=${CAPP_INSTALL_ROOT}/calibr8/lib"
  "-DGTest_ROOT=${CAPP_INSTALL_ROOT}/gtest"
  ${CALIBR8_OSX_RPATH_OPTIONS}
  ${TRILINOS_CMAKE_EXE_LINKER_FLAGS}
  DEPENDENCIES 
  scorec
  trilinos
  eigen
  gtest
  IGNORE_UNCOMMITTED
)
