find_package(Trilinos REQUIRED)
find_package(SCOREC REQUIRED)

function(assert_trilinos_pkg pkg_name)
  list(FIND Trilinos_PACKAGE_LIST ${pkg_name} idx)
  if(NOT idx GREATER -1)
    message(FATAL_ERROR "Trilinos: ${pkg_name} not enabled")
  endif()
  message(STATUS "Trilinos: ${pkg_name} is enabled!")
endfunction()

assert_trilinos_pkg(Amesos2)
assert_trilinos_pkg(Belos)
assert_trilinos_pkg(MueLu)
assert_trilinos_pkg(Pamgen)
assert_trilinos_pkg(Sacado)
assert_trilinos_pkg(MiniTensor)

list(REVERSE Trilinos_INCLUDE_DIRS)
list(REVERSE Trilinos_TPL_INCLUDE_DIRS)
list(REVERSE Trilinos_LIBRARIES)
list(REVERSE Trilinos_TPL_LIBRARIES)
list(REMOVE_DUPLICATES Trilinos_INCLUDE_DIRS)
list(REMOVE_DUPLICATES Trilinos_TPL_INCLUDE_DIRS)
list(REMOVE_DUPLICATES Trilinos_LIBRARIES)
list(REMOVE_DUPLICATES Trilinos_TPL_LIBRARIES)
list(REVERSE Trilinos_INCLUDE_DIRS)
list(REVERSE Trilinos_TPL_INCLUDE_DIRS)
list(REVERSE Trilinos_LIBRARIES)
list(REVERSE Trilinos_TPL_LIBRARIES)
