capp_package(
  GIT_URL https://github.com/HDFGroup/hdf5.git
  COMMIT 8b5cac6bc498546efa5639f99bb7dbbc1a2d5d90
  OPTIONS 
  "-DBUILD_SHARED_LIBS=${CALIBR8_BUILD_SHARED_LIBS}"
  "-DBUILD_TESTING=OFF"
  "-DHDF5_BUILD_EXAMPLES=OFF"
  "-DHDF5_ENABLE_SZIP_SUPPORT=OFF"
  "-DHDF5_ENABLE_Z_LIB_SUPPORT=OFF"
  "-DHDF5_ENABLE_PARALLEL=ON"
  "-DHDF5_BUILD_FORTRAN=OFF"
  DEPENDENCIES 
  PYTHON_DEPENDENCIES 
  IGNORE_UNCOMMITTED
)
