capp_package(
  GIT_URL https://github.com/HDFGroup/hdf5.git
  COMMIT 8b5cac6bc498546efa5639f99bb7dbbc1a2d5d90
  OPTIONS 
  "-DBUILD_SHARED_LIBS=${CALIBR8_BUILD_SHARED_LIBS}"
  "-DBUILD_TESTING=OFF"
  "-DHDF5_BUILD_EXAMPLES=OFF"
  "-DHDF5_ENABLE_SZIP_SUPPORT=OFF"
  "-DHDF5_ENABLE_PARALLEL=ON"
  "-DHDF5_BUILD_FORTRAN=OFF"
  "-DHDF5_BUILD_CPP_LIB=OFF"
  "-DHDF5_ENABLE_Z_LIB_SUPPORT=ON"
  "-DZLIB_ROOT=${CAPP_INSTALL_ROOT}/zlib-ng"
  "-DZLIB_LIBRARY=${CALIBR8_ZLIB_PATH}"
  DEPENDENCIES 
  zlib-ng
  PYTHON_DEPENDENCIES 
  IGNORE_UNCOMMITTED
)
#  "-DBUILD_STATIC_LIBS=ON"
#  "-DONLY_SHARED_LIBS=OFF"
