capp_package(
  GIT_URL git@github.com:ibaned/parmetis.git
  COMMIT 0c3fba270b0187f59f533109dec1b6a8a928c16a
  OPTIONS
  "-DBUILD_SHARED_LIBS=${CALIBR8_BUILD_SHARED_LIBS}"
  "-DCMAKE_C_COMPILER=${CALIBR8_MPICC}"
  "-DCMAKE_CXX_COMPILER=${CALIBR8_MPICXX}"
  DEPENDENCIES 
  IGNORE_UNCOMMITTED
)
